/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/3d/world.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function World(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/3d/world.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action.play();
    });
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight
          name="bonfire_light"
          intensity={543.514}
          decay={2}
          color="#ff7c2f"
          position={[-1.164, -0.769, 1.373]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          name="rocks"
          geometry={nodes.rocks.geometry}
          material={materials.rock}
          position={[-2.83, -0.88, -2.03]}
          rotation={[Math.PI, -1.426, Math.PI]}
          scale={[0.335, 0.366, 0.353]}
        />
        <group
          name="plants"
          position={[-2.944, -0.946, -1.67]}
          rotation={[Math.PI, -0.63, Math.PI]}
        >
          <mesh
            name="NurbsPath013"
            geometry={nodes.NurbsPath013.geometry}
            material={materials.green_plant}
          />
          <mesh
            name="NurbsPath013_1"
            geometry={nodes.NurbsPath013_1.geometry}
            material={materials.rose_emissive}
          />
        </group>
        <mesh
          name="earth"
          geometry={nodes.earth.geometry}
          material={materials.ground}
          position={[-4.452, -0.956, -3.564]}
          scale={[26.298, 1, 27.06]}
        />
        <group name="tree_1" position={[-6.275, -0.905, -0.118]}>
          <mesh
            name="BezierCurve003"
            geometry={nodes.BezierCurve003.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve003_1"
            geometry={nodes.BezierCurve003_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group name="tree_2" position={[1.553, -1.27, -4.449]}>
          <mesh
            name="BezierCurve005"
            geometry={nodes.BezierCurve005.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve005_1"
            geometry={nodes.BezierCurve005_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group name="tree_4" position={[-1.037, -1.229, -6.24]}>
          <mesh
            name="BezierCurve006"
            geometry={nodes.BezierCurve006.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve006_1"
            geometry={nodes.BezierCurve006_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group name="tree_3" position={[-0.733, -1.072, -3.439]}>
          <mesh
            name="BezierCurve010"
            geometry={nodes.BezierCurve010.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve010_1"
            geometry={nodes.BezierCurve010_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group name="tree_5" position={[0.986, -1.155, -2.239]}>
          <mesh
            name="BezierCurve012"
            geometry={nodes.BezierCurve012.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve012_1"
            geometry={nodes.BezierCurve012_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group
          name="tree_6"
          position={[-1.442, -1.047, 2.804]}
          rotation={[0, 0.458, 0]}
        >
          <mesh
            name="BezierCurve014"
            geometry={nodes.BezierCurve014.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve014_1"
            geometry={nodes.BezierCurve014_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group
          name="tree_8"
          position={[-3.352, -0.939, -1.151]}
          rotation={[0, 0.458, 0]}
        >
          <mesh
            name="BezierCurve014"
            geometry={nodes.BezierCurve014.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve014_1"
            geometry={nodes.BezierCurve014_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <mesh
          name="tree_9"
          geometry={nodes.tree_9.geometry}
          material={materials.water}
          position={[-5.511, -1.75, -3.538]}
          scale={[2.834, 3.904, 2.472]}
        />
        <group name="tree_10" position={[-6.029, -1.035, 1.397]}>
          <mesh
            name="BezierCurve002"
            geometry={nodes.BezierCurve002.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve002_1"
            geometry={nodes.BezierCurve002_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group name="tree_11" position={[3.178, -0.929, -1.83]}>
          <mesh
            name="Sphere026"
            geometry={nodes.Sphere026.geometry}
            material={materials.tree_bush}
          />
          <mesh
            name="Sphere026_1"
            geometry={nodes.Sphere026_1.geometry}
            material={materials.tree_trunk}
          />
        </group>
        <group name="tree_12" position={[2.949, -0.885, -0.331]}>
          <mesh
            name="Sphere032"
            geometry={nodes.Sphere032.geometry}
            material={materials.tree_bush}
          />
          <mesh
            name="Sphere032_1"
            geometry={nodes.Sphere032_1.geometry}
            material={materials.tree_trunk}
          />
        </group>
        <group name="tree_13" position={[-2.473, -0.77, 1.171]}>
          <mesh
            name="Sphere005"
            geometry={nodes.Sphere005.geometry}
            material={materials.tree_bush}
          />
          <mesh
            name="Sphere005_1"
            geometry={nodes.Sphere005_1.geometry}
            material={materials.tree_trunk}
          />
        </group>
        <group
          name="tree_7"
          position={[-2.724, -0.981, -2.946]}
          rotation={[0, 0.458, 0]}
        >
          <mesh
            name="BezierCurve001"
            geometry={nodes.BezierCurve001.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            name="BezierCurve001_1"
            geometry={nodes.BezierCurve001_1.geometry}
            material={materials.tree_bush}
          />
        </group>
        <group
          name="avatar"
          position={[-0.504, -0.228, 0.546]}
          rotation={[-0.049, 0.408, 0.277]}
          scale={[1, 0.942, 1]}
        >
          <mesh
            name="Plane005"
            geometry={nodes.Plane005.geometry}
            material={materials["black tshirt"]}
          />
          <mesh
            name="Plane005_1"
            geometry={nodes.Plane005_1.geometry}
            material={materials.hair_black}
          />
          <mesh
            name="Plane005_2"
            geometry={nodes.Plane005_2.geometry}
            material={materials.skin}
          />
          <mesh
            name="Plane005_3"
            geometry={nodes.Plane005_3.geometry}
            material={materials.hair_grey}
          />
          <mesh
            name="Plane005_4"
            geometry={nodes.Plane005_4.geometry}
            material={materials.bronze}
          />
          <mesh
            name="Plane005_5"
            geometry={nodes.Plane005_5.geometry}
            material={materials.arch_glass}
          />
          <mesh
            name="Plane005_6"
            geometry={nodes.Plane005_6.geometry}
            material={materials.grey_dark}
          />
        </group>
        <group
          name="book_shelves"
          position={[0.014, 0.092, -0.608]}
          rotation={[0, 1.571, 0]}
        >
          <mesh
            name="Cube036"
            geometry={nodes.Cube036.geometry}
            material={materials.white}
          />
          <mesh
            name="Cube036_1"
            geometry={nodes.Cube036_1.geometry}
            material={materials.star_wars_cover}
          />
          <mesh
            name="Cube036_2"
            geometry={nodes.Cube036_2.geometry}
            material={materials.monkey_island_cover}
          />
          <mesh
            name="Cube036_3"
            geometry={nodes.Cube036_3.geometry}
            material={materials.old_book}
          />
          <mesh
            name="Cube036_4"
            geometry={nodes.Cube036_4.geometry}
            material={materials.two_towers}
          />
          <mesh
            name="Cube036_5"
            geometry={nodes.Cube036_5.geometry}
            material={materials.forest}
          />
          <mesh
            name="Cube036_6"
            geometry={nodes.Cube036_6.geometry}
            material={materials.sorcery}
          />
          <mesh
            name="Cube036_7"
            geometry={nodes.Cube036_7.geometry}
            material={materials.brown_wood}
          />
          <mesh
            name="Cube036_8"
            geometry={nodes.Cube036_8.geometry}
            material={materials.window_frame}
          />
        </group>
        <group
          name="chair"
          position={[-0.396, -0.511, 0.511]}
          rotation={[Math.PI / 2, 0, -0.525]}
          scale={0.252}
        >
          <mesh
            name="Cylinder090"
            geometry={nodes.Cylinder090.geometry}
            material={materials["smooth_plastic_black.001"]}
          />
          <mesh
            name="Cylinder090_1"
            geometry={nodes.Cylinder090_1.geometry}
            material={materials.metal_black}
          />
          <mesh
            name="Cylinder090_2"
            geometry={nodes.Cylinder090_2.geometry}
            material={materials.brown_wood}
          />
        </group>
        <group
          name="walls&floor"
          position={[0, -0.476, 0]}
          rotation={[0, 1.571, 0]}
        >
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.carpet}
          />
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={materials.wall_material}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials.window_frame}
          />
          <mesh
            name="Plane_3"
            geometry={nodes.Plane_3.geometry}
            material={materials.arch_glass}
          />
        </group>
        <group
          name="lamps"
          position={[-0.081, -0.125, 0.042]}
          rotation={[-1.484, 1.571, 0]}
          scale={0.041}
        >
          <mesh
            name="Sphere003"
            geometry={nodes.Sphere003.geometry}
            material={materials.emission}
          />
          <mesh
            name="Sphere003_1"
            geometry={nodes.Sphere003_1.geometry}
            material={materials.white_glass}
          />
        </group>
        <group
          name="NES"
          position={[0.408, -0.198, -0.338]}
          rotation={[-Math.PI, 1.571, 0]}
          scale={[-0.008, -0.001, -0.003]}
        >
          <mesh
            name="Cube193"
            geometry={nodes.Cube193.geometry}
            material={materials.white}
          />
          <mesh
            name="Cube193_1"
            geometry={nodes.Cube193_1.geometry}
            material={materials.rough_plastic_white}
          />
          <mesh
            name="Cube193_2"
            geometry={nodes.Cube193_2.geometry}
            material={materials["smooth_plastic_black.001"]}
          />
          <mesh
            name="Cube193_3"
            geometry={nodes.Cube193_3.geometry}
            material={materials.plastic_red}
          />
          <mesh
            name="Cube193_4"
            geometry={nodes.Cube193_4.geometry}
            material={materials.smooth_plastic_black}
          />
          <mesh
            name="Cube193_5"
            geometry={nodes.Cube193_5.geometry}
            material={materials.grey}
          />
          <mesh
            name="Cube193_6"
            geometry={nodes.Cube193_6.geometry}
            material={materials.rough_plastic_dark_grey}
          />
          <mesh
            name="Cube193_7"
            geometry={nodes.Cube193_7.geometry}
            material={materials.megaman}
          />
          <mesh
            name="Cube193_8"
            geometry={nodes.Cube193_8.geometry}
            material={materials.ff_nes}
          />
          <mesh
            name="Cube193_9"
            geometry={nodes.Cube193_9.geometry}
            material={materials.mario}
          />
          <mesh
            name="Cube193_10"
            geometry={nodes.Cube193_10.geometry}
            material={materials.metroid}
          />
          <mesh
            name="Cube193_11"
            geometry={nodes.Cube193_11.geometry}
            material={materials.zelda_snes}
          />
          <mesh
            name="Cube193_12"
            geometry={nodes.Cube193_12.geometry}
            material={materials.red_light}
          />
          <mesh
            name="Cube193_13"
            geometry={nodes.Cube193_13.geometry}
            material={materials.rough_plastic_white_logo}
          />
          <mesh
            name="Cube193_14"
            geometry={nodes.Cube193_14.geometry}
            material={materials.NES_LOGO}
          />
        </group>
        <mesh
          name="pc_monitor"
          geometry={nodes.pc_monitor.geometry}
          material={materials.green_emissive_rpg}
          position={[0.002, 0.086, -0.3]}
        />
        <group
          name="office_plants"
          position={[0.002, 0.011, -0.177]}
          rotation={[0, 1.571, 0]}
          scale={0.647}
        >
          <mesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={materials.brown_wood}
          />
          <mesh
            name="Cube004_1"
            geometry={nodes.Cube004_1.geometry}
            material={materials.earth}
          />
          <mesh
            name="Cube004_2"
            geometry={nodes.Cube004_2.geometry}
            material={materials.green_plant}
          />
        </group>
        <group
          name="posters"
          position={[0.054, 0.177, -0.396]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.168, 1, 0.233]}
        >
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={materials.et}
          />
          <mesh
            name="Plane002_1"
            geometry={nodes.Plane002_1.geometry}
            material={materials.final_fantasy}
          />
          <mesh
            name="Plane002_2"
            geometry={nodes.Plane002_2.geometry}
            material={materials.b2f}
          />
          <mesh
            name="Plane002_3"
            geometry={nodes.Plane002_3.geometry}
            material={materials.monkey_island}
          />
          <mesh
            name="Plane002_4"
            geometry={nodes.Plane002_4.geometry}
            material={materials.mega_man}
          />
        </group>
        <group name="pc&floppies" position={[0.115, 0.014, -0.371]}>
          <mesh
            name="Plane015"
            geometry={nodes.Plane015.geometry}
            material={materials.sticky_yellow_scribbles}
          />
          <mesh
            name="Plane015_1"
            geometry={nodes.Plane015_1.geometry}
            material={materials.sticky_blue_scribbles}
          />
          <mesh
            name="Plane015_2"
            geometry={nodes.Plane015_2.geometry}
            material={materials.sticky_green_scribbles}
          />
          <mesh
            name="Plane015_3"
            geometry={nodes.Plane015_3.geometry}
            material={materials.sticky_pink}
          />
          <mesh
            name="Plane015_4"
            geometry={nodes.Plane015_4.geometry}
            material={materials.white_striped_paper}
          />
          <mesh
            name="Plane015_5"
            geometry={nodes.Plane015_5.geometry}
            material={materials.floppy_disk_black}
          />
          <mesh
            name="Plane015_6"
            geometry={nodes.Plane015_6.geometry}
            material={materials.silver_metal}
          />
          <mesh
            name="Plane015_7"
            geometry={nodes.Plane015_7.geometry}
            material={materials.floppy_disk_blue}
          />
          <mesh
            name="Plane015_8"
            geometry={nodes.Plane015_8.geometry}
            material={materials.rough_plastic_beige}
          />
          <mesh
            name="Plane015_9"
            geometry={nodes.Plane015_9.geometry}
            material={materials.rough_plastic_dark_beige}
          />
          <mesh
            name="Plane015_10"
            geometry={nodes.Plane015_10.geometry}
            material={materials.rough_plastic_GREY}
          />
          <mesh
            name="Plane015_11"
            geometry={nodes.Plane015_11.geometry}
            material={materials.green_emission}
          />
          <mesh
            name="Plane015_12"
            geometry={nodes.Plane015_12.geometry}
            material={materials.metalic_light_grey}
          />
          <mesh
            name="Plane015_13"
            geometry={nodes.Plane015_13.geometry}
            material={materials.grey_dark}
          />
          <mesh
            name="Plane015_14"
            geometry={nodes.Plane015_14.geometry}
            material={materials["smooth_plastic_black.001"]}
          />
        </group>
        <group
          name="table"
          position={[0.071, -0.538, -0.354]}
          rotation={[0, 1.571, 0]}
          scale={[1, 1, 0.932]}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.brown_wood}
          />
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials.white_wood}
          />
          <mesh
            name="Cube_2"
            geometry={nodes.Cube_2.geometry}
            material={materials.bronze}
          />
          <mesh
            name="Cube_3"
            geometry={nodes.Cube_3.geometry}
            material={materials.white}
          />
          <mesh
            name="Cube_4"
            geometry={nodes.Cube_4.geometry}
            material={materials.smooth_plastic_black}
          />
        </group>
        <group
          name="table_pens"
          position={[0.212, -0.155, -0.322]}
          rotation={[0, 1.571, 0]}
        >
          <mesh
            name="Cone008"
            geometry={nodes.Cone008.geometry}
            material={materials.pencil}
          />
          <mesh
            name="Cone008_1"
            geometry={nodes.Cone008_1.geometry}
            material={materials.pencil_tip}
          />
          <mesh
            name="Cone008_2"
            geometry={nodes.Cone008_2.geometry}
            material={materials.pen_holder}
          />
        </group>
        <group
          name="VCR"
          position={[-0.467, -0.175, -0.445]}
          rotation={[0, -1.571, 0]}
          scale={[0.056, 0.383, 0.466]}
        >
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={materials.rough_plastic_beige}
          />
          <mesh
            name="Cube053_1"
            geometry={nodes.Cube053_1.geometry}
            material={materials.smooth_plastic_black}
          />
          <mesh
            name="Cube053_2"
            geometry={nodes.Cube053_2.geometry}
            material={materials["smooth_plastic_black.001"]}
          />
          <mesh
            name="Cube053_3"
            geometry={nodes.Cube053_3.geometry}
            material={materials.gold_text}
          />
          <mesh
            name="Cube053_4"
            geometry={nodes.Cube053_4.geometry}
            material={materials.monitor_glass}
          />
          <mesh
            name="Cube053_5"
            geometry={nodes.Cube053_5.geometry}
            material={materials.arch_glass}
          />
          <mesh
            name="Cube053_6"
            geometry={nodes.Cube053_6.geometry}
            material={materials.white}
          />
        </group>
        <group name="my_book" position={[-0.238, -0.16, 0.55]}>
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials.white}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials.old_book}
          />
        </group>
        <mesh
          name="avatar001"
          geometry={nodes.avatar001.geometry}
          material={materials.hair_black}
          position={[-0.45, 0.188, 0.553]}
          rotation={[-0.049, 0.408, 0.277]}
          scale={[1, 0.942, 1]}
        />
        <mesh
          name="fire_logs"
          geometry={nodes.fire_logs.geometry}
          material={materials.fire_log}
          position={[-1.104, -0.86, 1.344]}
          rotation={[-1.563, 0.204, -1.608]}
          scale={[0.057, 0.245, 0.051]}
        />
        <mesh
          name="flame_red"
          geometry={nodes.flame_red.geometry}
          material={materials.flameRed}
          position={[-1.174, -0.723, 1.38]}
          scale={0.413}
        />
        <mesh
          name="flame_white"
          geometry={nodes.flame_white.geometry}
          material={materials.flameWhite}
          position={[-1.146, -0.651, 1.365]}
          rotation={[0.244, 0, 0]}
          scale={0.699}
        />
        <mesh
          name="flame_yellow"
          geometry={nodes.flame_yellow.geometry}
          material={materials.flameYellow}
          position={[-1.167, -0.673, 1.38]}
          rotation={[0.244, 0, 0]}
          scale={0.544}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d/world.glb");
